ECommerce/Models/Companhia.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web;

namespace ECommerce.Models
{
    public class Companhia
    {
        [Key]
        public int CompanhiaId { get; set; }


        [Required(ErrorMessage = "O campo Nome é requerido")]
        [Index("Departamento_Nome_Index", IsUnique = true)]
        [MaxLength(50, ErrorMessage = "O campo Nome recebe no máximo 50 caracteres")]
        [Display(Name = "Nome")]
        public string Nome { get; set; }


        [Required(ErrorMessage = "O campo Telefone é requerido")]
        [MaxLength(50, ErrorMessage = "O campo Telefone recebe no máximo 50 caracteres")]
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Telefone")]
        public string Telefone { get; set; }


        [Required(ErrorMessage = "O campo Endereço é requerido")]
        [MaxLength(100, ErrorMessage = "O campo Endereço recebe no máximo 100 caracteres")]
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Endereço")]
        public string Endereco { get; set; }


        [DataType(DataType.ImageUrl)]
        [Display(Name = "Imagem")]
        public string Logo { get; set; }


        [NotMapped]
        public HttpPostedFileBase LogoArquivo { get; set; }


        [Required(ErrorMessage = "O campo Deparmento é requerido")]
        [Display(Name="Departamento")]
        public int DepartamentoId { get; set; }


        [Required(ErrorMessage = "O campo Cidade é requerido")]
        [Display(Name="Cidade")]
        public int CidadeId { get; set; }


        public virtual Departamento Departamento { get; set; }
        public virtual Cidade Cidades { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Categoria> Categoria { get; set; }

    }
}

ECommerce/Controllers/CompanhiaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ECommerce.Models;
using ECommerce.Helpers;

namespace ECommerce.Controllers
{
    public class CompanhiaController : Controller
    {
        private ECommerceContext db = new ECommerceContext();

        // GET: Companhia
        public ActionResult Index()
        {
            var companhias = db.Companhias.Include(c => c.Cidades).Include(c => c.Departamento);
            return View(companhias.ToList());
        }

        public JsonResult GetCidades(int departamentoId)
        {
            db.Configuration.ProxyCreationEnabled = false;
            var cidades = db.Cidades.Where(c => c.DepartamentoId == departamentoId);
            return Json(cidades);
        }

        // GET: Companhia/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Companhia companhia = db.Companhias.Find(id);
            if (companhia == null)
            {
                return HttpNotFound();
            }
            return View(companhia);
        }

        // GET: Companhia/Create
        public ActionResult Create()
        {
            ViewBag.CidadeId = new SelectList(CombosHelper.GetCidades(), "CidadeId", "Nome");
            ViewBag.DepartamentoId = new SelectList(CombosHelper.GetDepartamentos(), "DepartamentoId", "Nome");
            return View();
        }

        // POST: Companhia/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Companhia companhia)
        {
            if (ModelState.IsValid)
            {
                db.Companhias.Add(companhia);
                db.SaveChanges();

                if (companhia.LogoArquivo != null)
                {
                    var foto = string.Empty;
                    var pasta = "~/img/Logos";
                    var arquivo = string.Format("{0}.jpg", companhia.CompanhiaId);

                    var response = FilesHelper.UploadFoto(companhia.LogoArquivo, pasta, arquivo);
                    if (response)
                    {
                        foto = string.Format("{0}/{1}", pasta, arquivo);
                        companhia.Logo = foto;
                        db.Entry(companhia).State = EntityState.Modified;
                        db.SaveChanges();
                    }

                }

                return RedirectToAction("Index");
            }

            ViewBag.CidadeId = new SelectList(CombosHelper.GetCidades(), "CidadeId", "Nome", companhia.CidadeId);
            ViewBag.DepartamentoId = new SelectList(CombosHelper.GetDepartamentos(), "DepartamentoId", "Nome", companhia.DepartamentoId);
            return View(companhia);
        }

        // GET: Companhia/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Companhia companhia = db.Companhias.Find(id);
            if (companhia == null)
            {
                return HttpNotFound();
            }
            ViewBag.CidadeId = new SelectList(CombosHelper.GetCidades(), "CidadeId", "Nome", companhia.CidadeId);
            ViewBag.DepartamentoId = new SelectList(CombosHelper.GetCidades(), "DepartamentoId", "Nome", companhia.DepartamentoId);
            return View(companhia);
        }

        // POST: Companhia/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CompanhiaId,Nome,Telefone,Endereco,Logo,DepartamentoId,CidadeId")] Companhia companhia)
        {
            if (companhia.LogoArquivo != null)
            {
                var foto = string.Empty;
                var pasta = "~/img/Logos";
                var arquivo = string.Format("{0}.jpg", companhia.CompanhiaId);

                var response = FilesHelper.UploadFoto(companhia.LogoArquivo, pasta, arquivo);
                if (response)
                {
                    foto = string.Format("{0}/{1}", pasta, arquivo);
                    companhia.Logo = foto;
                }

                db.Entry(companhia).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }



            ViewBag.CidadeId = new SelectList(CombosHelper.GetCidades(), "CidadeId", "Nome", companhia.CidadeId);
            ViewBag.DepartamentoId = new SelectList(CombosHelper.GetCidades(), "DepartamentoId", "Nome", companhia.DepartamentoId);
            return View(companhia);
        }

        // GET: Companhia/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Companhia companhia = db.Companhias.Find(id);
            if (companhia == null)
            {
                return HttpNotFound();
            }
            return View(companhia);
        }

        // POST: Companhia/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Companhia companhia = db.Companhias.Find(id);
            db.Companhias.Remove(companhia);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ECommerce/Views/Companhia/Create.cshtml
@model ECommerce.Models.Companhia

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Companhia", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Companhia</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LogoArquivo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="btn btn-default btn-file">
                    @Html.TextBoxFor(modelo => modelo.LogoArquivo, new { type = "file" })
                </span>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepartamentoId, "DepartamentoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DepartamentoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DepartamentoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CidadeId, "CidadeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CidadeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CidadeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript">
        $(document).ready(function () {
            $("#DepartamentoId").change(function () {
                $("#CidadeId").empty();
			    $("#CidadeId").append('<option value="0">[Selecione  uma Cidade..]</option>');
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("GetCidades")',
                    dataType: 'json',
                    data: { departamentoId: $("#DepartamentoId").val() },
                    success: function (data) {
                        $.each(data, function (i, data) {
                            $("#CidadeId").append('<option value="'
                             + data.CidadeId + '">'
                             + data.Nome + '</option>');
                        });
                    },
                    error: function (ex) {
                        alert('Falha ao buscar cidades.' + ex);
                    }
                });
                return false;
            })
        });
</script>
}

ECommerce/Views/Companhia/Delete.cshtml
@model ECommerce.Models.Companhia

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Companhia</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cidades.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cidades.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Departamento.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Departamento.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Endereco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Endereco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Logo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Logo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ECommerce/Views/Companhia/Details.cshtml
@model ECommerce.Models.Companhia

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Companhia</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cidades.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cidades.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Departamento.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Departamento.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Endereco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Endereco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Logo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Logo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CompanhiaId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ECommerce/Views/Companhia/Edit.cshtml
@model ECommerce.Models.Companhia

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Create", "Companhia", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Companhia</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CompanhiaId)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
            </div>
        </div>

       
        <div class="form-group">
            @Html.LabelFor(model => model.LogoArquivo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="btn btn-default btn-file">
                    @Html.TextBoxFor(modelo => modelo.LogoArquivo, new { type = "file" })
                </span>
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.DepartamentoId, "DepartamentoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DepartamentoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DepartamentoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CidadeId, "CidadeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CidadeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CidadeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript">
        $(document).ready(function () {
            $("#DepartamentoId").change(function () {
                $("#CidadeId").empty();
			    $("#CidadeId").append('<option value="0">[Selecione  uma Cidade..]</option>');
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("GetCidades")',
                    dataType: 'json',
                    data: { departamentId: $("#DepartamentoId").val() },
                    success: function (data) {
                        $.each(data, function (i, data) {
                            $("#CidadeId").append('<option value="'
                             + data.CidadeId + '">'
                             + data.Nome + '</option>');
                        });
                    },
                    error: function (ex) {
                        alert('Falha ao buscar cidades.' + ex);
                    }
                });
                return false;
            })
        });
</script>

}

ECommerce/Views/Companhia/Index.cshtml
@model IEnumerable<ECommerce.Models.Companhia>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Cidades.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Departamento.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Endereco)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Logo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Cidades.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Departamento.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Telefone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Endereco)
        </td>
        <td>
            @if (!string.IsNullOrEmpty(item.Logo))
            {
                <img src="@Url.Content(item.Logo)" alt="Image" style="width:100px;height:150px;max-width: 100%; height: auto;" />

            }
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.CompanhiaId }) |
            @Html.ActionLink("Details", "Details", new { id=item.CompanhiaId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CompanhiaId })
        </td>
    </tr>
}

</table>