ECommerce/Models/User.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web;

namespace ECommerce.Models
{
    public class User
    {
        [Key]
        public int UserId { get; set; }


        [Required(ErrorMessage = "O campo E-Mail é requerido")]
        [Index("User_Username_Index", IsUnique = true)]
        [MaxLength(250, ErrorMessage = "O campo E-Mail recebe no máximo 25 0 caracteres")]
        [Display(Name = "E-Mail")]
        public string UserName { get; set; }


        [Required(ErrorMessage = "O campo Nome é requerido")]
        [Index("User_Nome_Index", IsUnique = true)]
        [MaxLength(50, ErrorMessage = "O campo Nome recebe no máximo 50 caracteres")]
        [Display(Name = "Nome")] 
        public string Nome { get; set; }


        [Required(ErrorMessage = "O campo Sobrenome é requerido!!")]
        [MaxLength(50, ErrorMessage = "O campo Sobrenome recebe no máximo 50 caracteres")]
        [Display(Name = "Sobrenome")]
        public string Sobrenome { get; set; }


        [Required(ErrorMessage = "O campo Telefone é requerido!!")]
        [MaxLength(50, ErrorMessage = "O campo Telefone recebe no máximo 50 caracteres")]
        [Display(Name = "Telefone")]
        [DataType(DataType.PhoneNumber)]
        public string Telefone { get; set; }


        [Required(ErrorMessage = "O campo Endereço é requerido!!")]
        [MaxLength(100, ErrorMessage = "O campo Endereço recebe no máximo 50 caracteres")]
        [Display(Name = "Endereço")]
        public string Endereco { get; set; }


        [Display(Name = "Imagem")]
        [DataType(DataType.ImageUrl)]
        public string Imagem { get; set; }


        [NotMapped]
        public HttpPostedFileBase ImagemArquivo { get; set; }


        [Required(ErrorMessage = "O campo Departamento é requerido!!")]
        [Display(Name = "Departamento")]
        public int DepartamentoId { get; set; }


        [Required(ErrorMessage = "O campo Cidade é requerido!!")]
        [Display(Name = "Cidade")]
        public int CidadeId { get; set; }


        [Required(ErrorMessage = "O campo Cidade é requerido!!")]
        [Display(Name = "Companhia")]
        public int CompanhiaId { get; set; }


        [Display(Name = "Usuário")]
        public string NomeCompleto { get { return string.Format("{0} {1}", Nome, Sobrenome); } }


        public virtual Departamento Departamentos { get; set; }
        public virtual Cidade Cidades { get; set; }
        public virtual Companhia Companhia { get; set; }
    }
}

ECommerce/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ECommerce.Models;
using ECommerce.Helpers;
using static ECommerce.Helpers.UserHelper;

namespace ECommerce.Controllers
{
    public class UsersController : Controller
    {
        private ECommerceContext db = new ECommerceContext();

        // GET: Users
        public ActionResult Index()
        {
            var users = db.Users.Include(u => u.Cidades).Include(u => u.Companhia).Include(u => u.Departamentos);
            return View(users.ToList());
        }

        public JsonResult GetCidades(int departamentoId)
        {
            db.Configuration.ProxyCreationEnabled = false;
            var cidades = db.Cidades.Where(c => c.DepartamentoId == departamentoId);
            return Json(cidades);
        }

        // GET: Users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            ViewBag.CidadeId = new SelectList(CombosHelper.GetCidades(), "CidadeId", "Nome");
            ViewBag.CompanhiaId = new SelectList(CombosHelper.GetCompanhia(), "CompanhiaId", "Nome");
            ViewBag.DepartamentoId = new SelectList(CombosHelper.GetDepartamentos(), "DepartamentoId", "Nome");
            return View();
        }

        // POST: Users/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(User user)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(user);
                db.SaveChanges();
                UsersHelper.CreateUserASP(user.UserName, "User");

                if (user.ImagemArquivo != null)
                {
                    var foto = string.Empty;
                    var pasta = "~/img/Users";
                    var arquivo = string.Format("{0}.jpg", user.UserId);

                    var response = FilesHelper.UploadFoto(user.ImagemArquivo, pasta, arquivo);
                    if (response)
                    {
                        foto = string.Format("{0}/{1}", pasta, arquivo);
                        user.Imagem = foto;
                        db.Entry(user).State = EntityState.Modified;
                        db.SaveChanges();
                    }
                }
                return RedirectToAction("Index");
            }
            ViewBag.CidadeId = new SelectList(CombosHelper.GetCidades(), "CidadeId", "Nome");
            ViewBag.CompanhiaId = new SelectList(CombosHelper.GetCompanhia(), "CompanhiaId", "Nome");
            ViewBag.DepartamentoId = new SelectList(CombosHelper.GetDepartamentos(), "DepartamentoId", "Nome");
            return View(user);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            ViewBag.CidadeId = new SelectList(CombosHelper.GetCidades(), "CidadeId", "Nome");
            ViewBag.CompanhiaId = new SelectList(CombosHelper.GetCompanhia(), "CompanhiaId", "Nome");
            ViewBag.DepartamentoId = new SelectList(CombosHelper.GetDepartamentos(), "DepartamentoId", "Nome");
            return View(user);
        }

        // POST: Users/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(User user)
        {
            if (ModelState.IsValid)
            {
                if (user.ImagemArquivo != null)
                {
                    var foto = string.Empty;
                    var pasta = "~/img/Users";
                    var arquivo = string.Format("{0}.jpg", user.UserId);

                    var response = FilesHelper.UploadFoto(user.ImagemArquivo, pasta, arquivo);
                    if (response)
                    {
                        foto = string.Format("{0}/{1}", pasta, arquivo);
                        user.Imagem = foto;
                    }
                }

                var db2 = new ECommerceContext();
                var currentuser = db2.Users.Find(user.UserId);
                if (currentuser.UserName != user.UserName)
                {
                    UserHelper.UsersHelper.UpdateUserName(currentuser.UserName, user.UserName);
                }
                db2.Dispose();

                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                UserHelper.UsersHelper.UpdateUserName(user.Nome, "User");
                return RedirectToAction("Index");
            }
            ViewBag.CidadeId = new SelectList(CombosHelper.GetCidades(), "CidadeId", "Nome");
            ViewBag.CompanhiaId = new SelectList(CombosHelper.GetCompanhia(), "CompanhiaId", "Nome");
            ViewBag.DepartamentoId = new SelectList(CombosHelper.GetDepartamentos(), "DepartamentoId", "Nome");
            return View(user);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ECommerce/Views/Users/Create.cshtml
@model ECommerce.Models.User

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Users", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sobrenome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sobrenome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sobrenome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Imagem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="btn btn-default btn-file">
                    @Html.TextBoxFor(modelo => modelo.ImagemArquivo, new { type = "file" })
                </span>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepartamentoId, "DepartamentoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DepartamentoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DepartamentoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CidadeId, "CidadeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CidadeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CidadeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CompanhiaId, "CompanhiaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CompanhiaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CompanhiaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ECommerce/Views/Users/Delete.cshtml
@model ECommerce.Models.User

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cidades.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cidades.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Companhia.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Companhia.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Departamentos.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Departamentos.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sobrenome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sobrenome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Endereco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Endereco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Imagem)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Imagem)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ECommerce/Views/Users/Details.cshtml
@model ECommerce.Models.User

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cidades.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cidades.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Companhia.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Companhia.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Departamentos.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Departamentos.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sobrenome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sobrenome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Endereco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Endereco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Imagem)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Imagem)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.UserI }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ECommerce/Views/Users/Edit.cshtml
@model ECommerce.Models.User

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UserId)

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sobrenome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sobrenome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sobrenome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Imagem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Imagem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Imagem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepartamentoId, "DepartamentoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DepartamentoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DepartamentoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CidadeId, "CidadeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CidadeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CidadeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CompanhiaId, "CompanhiaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CompanhiaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CompanhiaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ECommerce/Views/Users/Index.cshtml
@model IEnumerable<ECommerce.Models.User>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Cidades.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Companhia.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Departamentos.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sobrenome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Endereco)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Imagem)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Cidades.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Companhia.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Departamentos.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sobrenome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Telefone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Endereco)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Imagem)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.UserId }) |
            @Html.ActionLink("Details", "Details", new { id=item.UserId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.UserId })
        </td>
    </tr>
}

</table>